nick: hjertnes
url: https://hjertnes.social/twtxt.txt
file: ~/Code/twtxt/twtxt.txt
following:
  eli_oat: https://txt.eli.li/twtxt/twtxt.txt
  felix: https://felix.plesoianu.ro/twtxt.txt
  gbmor: https://gbmor.dev/twtxt.txt
  golang_news: https://feeds.twtxt.net/golang_news/twtxt.txt
  iolfree: https://tilde.club/~iolfree/twtxt.txt
  jack: http://tilde.club/~jbaty/twtxt.txt
  johanbove: https://johanbove.info/twtxt.txt
  lahvak: http://lahvak.github.io/twtxt/twtxt.txt
  lucidiot: https://tilde.town/~lucidiot/twtxt.txt
  marado: https://tilde.pt/~marado/twtxt.txt
  mdom: https://www.domgoergen.com/twtxt/mdom.txt
  melyanna: https://tilde.club/~melyanna/twtxt.txt
  pbatch: https://pbat.ch/twtxt.txt
discloseidentity: true
