nick: hjertnes
url: https://hjertnes.social/twtxt.txt
file: ~/Code/twtxt/twtxt.txt
following:
  edsu: http://edsu.github.io/twtxt/twtxt.txt
  eli_oat: https://txt.eli.li/twtxt/twtxt.txt
  esc: http://escowles.github.io/tw.txt
  felix: https://felix.plesoianu.ro/twtxt.txt
  freemor: https://freemor.homelinux.net/~freemor/twtxt.txt
  fundor333: https://fundor333.com/twtxt.txt
  gbmor: https://gbmor.dev/twtxt.txt
  gil: https://tilde.pt/~gil/twtxt.txt
  golang_news: https://feeds.twtxt.net/golang_news/twtxt.txt
  iolfree: https://tilde.club/~iolfree/twtxt.txt
  jack: http://tilde.club/~jbaty/twtxt.txt
  jb55: https://jb55.com/twtxt.txt
  johanbove: https://johanbove.info/twtxt.txt
  kodedninja: https://t.seed.hex22.org/twtxt.txt
  lahvak: http://lahvak.github.io/twtxt/twtxt.txt
  leo: https://www.gkbrk.com/twtxt.txt
  lucidiot: https://tilde.town/~lucidiot/twtxt.txt
  marado: https://tilde.pt/~marado/twtxt.txt
  mdom: https://www.domgoergen.com/twtxt/mdom.txt
  mdosch: https://mdosch.de/twtxt.txt
  melyanna: https://tilde.club/~melyanna/twtxt.txt
  moon: https://tilde.town/~mox/moon.txt
  mox: https://tilde.town/~mox/twtxt.txt
  mr_woggle: https://tilde.town/~mr_woggle/twtxt.txt
  nblade: http://nblade.sdf.org/twtxt/twtxt.txt
  nonlinear: https://nonlinear.radiofreqs.space/twtxt.txt
  oevl: https://oevl.info/twtxt.txt
  pbatch: https://pbat.ch/twtxt.txt
  pelmel: http://pelmel.org/twtxt.txt
  prologic: https://twtxt.net/user/prologic/twtxt.txt
  quite: https://lublin.se/twtxt.txt
  reednj: http://twtxt.xyz/user/8c2b4bbfa328944ba.txt
  ruebot: http://ruebot.github.io/twtxt/twtxt.txt
  sixbitproxywax: https://sixbitproxywax.com/twtxt.txt
  svf: http://scott.vranesh-fallin.com/twtxt.txt
  tildebeast: https://tilde.team/~tildebeast/twtxt/twtxt.txt
  tolstoevsky: https://tolstoevsky.ml/twtxt.txt
  tux0r: https://twtxt.rosaelefanten.org/
  twet: https://lublin.se/twet.txt
  tx: https://shroom.party/twtxt.txt
  vinc: https://vinc.cc/twtxt.txt
  von: https://tilde.town/~von/twtxt.txt
  xandkar: https://xandkar.net/twtxt.txt
discloseidentity: true
